### PR TITLE
fix bad import

### PR DESCRIPTION
**Pull request by cwhittl**

### CODE REVIEW

**Comment by damienleroux** [comment]
Hello. Why transforming "Tooptip" to "ToolTip"?

**Review by damienleroux — APPROVED** [review]

**Comment by cwhittl** [comment]
It was for consistency.  It was one way in one example and another way in
another example.
It could really be either but needed to be the same.

**Comment by damienleroux** [comment]
Thank you for contributing. I updated examples and readme to have `Tooltip` everywhere.

**Comment by cwhittl** [comment]
Thank you for making the component!

**Pull request merged**
